// (c) Copyright Ascensio System SIA 2026
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package docspace_api_sdk

import (
	"encoding/json"
	"fmt"
)

// EmployeeActivationStatus [0 - Not activated, 1 - Activated, 2 - Pending, 4 - Auto generated]
type EmployeeActivationStatus int32

// List of EmployeeActivationStatus
const (
	EMPLOYEEACTIVATIONSTATUS_NotActivated EmployeeActivationStatus = 0
	EMPLOYEEACTIVATIONSTATUS_Activated EmployeeActivationStatus = 1
	EMPLOYEEACTIVATIONSTATUS_Pending EmployeeActivationStatus = 2
	EMPLOYEEACTIVATIONSTATUS_AutoGenerated EmployeeActivationStatus = 4
)

// All allowed values of EmployeeActivationStatus enum
var AllowedEmployeeActivationStatusEnumValues = []EmployeeActivationStatus{
	0,
	1,
	2,
	4,
}

func (v *EmployeeActivationStatus) UnmarshalJSON(src []byte) error {
	var value int32
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EmployeeActivationStatus(value)
	for _, existing := range AllowedEmployeeActivationStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EmployeeActivationStatus", value)
}

// NewEmployeeActivationStatusFromValue returns a pointer to a valid EmployeeActivationStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEmployeeActivationStatusFromValue(v int32) (*EmployeeActivationStatus, error) {
	ev := EmployeeActivationStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EmployeeActivationStatus: valid values are %v", v, AllowedEmployeeActivationStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EmployeeActivationStatus) IsValid() bool {
	for _, existing := range AllowedEmployeeActivationStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EmployeeActivationStatus value
func (v EmployeeActivationStatus) Ptr() *EmployeeActivationStatus {
	return &v
}

type NullableEmployeeActivationStatus struct {
	value *EmployeeActivationStatus
	isSet bool
}

func (v NullableEmployeeActivationStatus) Get() *EmployeeActivationStatus {
	return v.value
}

func (v *NullableEmployeeActivationStatus) Set(val *EmployeeActivationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableEmployeeActivationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableEmployeeActivationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmployeeActivationStatus(val *EmployeeActivationStatus) *NullableEmployeeActivationStatus {
	return &NullableEmployeeActivationStatus{value: val, isSet: true}
}

func (v NullableEmployeeActivationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmployeeActivationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

