// (c) Copyright Ascensio System SIA 2026
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package docspace_api_sdk

import (
	"encoding/json"
)

// checks if the EditHistoryChangesWrapper type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EditHistoryChangesWrapper{}

// EditHistoryChangesWrapper The parameters of the file editing history.
type EditHistoryChangesWrapper struct {
	User *EditHistoryAuthor `json:"user,omitempty"`
	Created *ApiDateTime `json:"created,omitempty"`
	// The document hash generated by the SHA-256 algorithm.
	DocumentSha256 NullableString `json:"documentSha256,omitempty"`
}

// NewEditHistoryChangesWrapper instantiates a new EditHistoryChangesWrapper object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditHistoryChangesWrapper() *EditHistoryChangesWrapper {
	this := EditHistoryChangesWrapper{}
	return &this
}

// NewEditHistoryChangesWrapperWithDefaults instantiates a new EditHistoryChangesWrapper object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditHistoryChangesWrapperWithDefaults() *EditHistoryChangesWrapper {
	this := EditHistoryChangesWrapper{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *EditHistoryChangesWrapper) GetUser() EditHistoryAuthor {
	if o == nil || IsNil(o.User) {
		var ret EditHistoryAuthor
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditHistoryChangesWrapper) GetUserOk() (*EditHistoryAuthor, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *EditHistoryChangesWrapper) IsUserSet() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given EditHistoryAuthor and assigns it to the User field.
func (o *EditHistoryChangesWrapper) SetUser(v EditHistoryAuthor) {
	o.User = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *EditHistoryChangesWrapper) GetCreated() ApiDateTime {
	if o == nil || IsNil(o.Created) {
		var ret ApiDateTime
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditHistoryChangesWrapper) GetCreatedOk() (*ApiDateTime, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *EditHistoryChangesWrapper) IsCreatedSet() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given ApiDateTime and assigns it to the Created field.
func (o *EditHistoryChangesWrapper) SetCreated(v ApiDateTime) {
	o.Created = &v
}

// GetDocumentSha256 returns the DocumentSha256 field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EditHistoryChangesWrapper) GetDocumentSha256() string {
	if o == nil || IsNil(o.DocumentSha256.Get()) {
		var ret string
		return ret
	}
	return *o.DocumentSha256.Get()
}

// GetDocumentSha256Ok returns a tuple with the DocumentSha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EditHistoryChangesWrapper) GetDocumentSha256Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DocumentSha256.Get(), o.DocumentSha256.IsSet()
}

// HasDocumentSha256 returns a boolean if a field has been set.
func (o *EditHistoryChangesWrapper) IsDocumentSha256Set() bool {
	if o != nil && o.DocumentSha256.IsSet() {
		return true
	}

	return false
}

// SetDocumentSha256 gets a reference to the given NullableString and assigns it to the DocumentSha256 field.
func (o *EditHistoryChangesWrapper) SetDocumentSha256(v string) {
	o.DocumentSha256.Set(&v)
}
// SetDocumentSha256Nil sets the value for DocumentSha256 to be an explicit nil
func (o *EditHistoryChangesWrapper) SetDocumentSha256Nil() {
	o.DocumentSha256.Set(nil)
}

// UnsetDocumentSha256 ensures that no value is present for DocumentSha256, not even an explicit nil
func (o *EditHistoryChangesWrapper) UnsetDocumentSha256() {
	o.DocumentSha256.Unset()
}

func (o EditHistoryChangesWrapper) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EditHistoryChangesWrapper) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if o.DocumentSha256.IsSet() {
		toSerialize["documentSha256"] = o.DocumentSha256.Get()
	}
	return toSerialize, nil
}

type NullableEditHistoryChangesWrapper struct {
	value *EditHistoryChangesWrapper
	isSet bool
}

func (v NullableEditHistoryChangesWrapper) Get() *EditHistoryChangesWrapper {
	return v.value
}

func (v *NullableEditHistoryChangesWrapper) Set(val *EditHistoryChangesWrapper) {
	v.value = val
	v.isSet = true
}

func (v NullableEditHistoryChangesWrapper) IsSet() bool {
	return v.isSet
}

func (v *NullableEditHistoryChangesWrapper) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditHistoryChangesWrapper(val *EditHistoryChangesWrapper) *NullableEditHistoryChangesWrapper {
	return &NullableEditHistoryChangesWrapper{value: val, isSet: true}
}

func (v NullableEditHistoryChangesWrapper) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditHistoryChangesWrapper) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

